### PR TITLE
fix the current streak counter

### PR DESCRIPTION
**Pull request by vunderkind**
@Naramsim — new PR pushing to the staging branch. I've also fixed the `value of attributes` undefined issue. Let me know if you can run this!

Snapshot from my computer ATM:
Screenshot 2023-01-08 at 19 58 08

Thank you 🙏🏿

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi, the code now runs fine. 

Two things: 

when on a profile, switching tab (Repositories, Projects, Packages...) and then back to Overview, the stats aren't displayed anymore. In the past, we used to watch for an element to become present and then attach the stats. Don't know if they removed the element we were watching. 

Also, the stats for fully-contributed calendars stop at 366 days, in the past it wasn't so.

Both the comments above aren't related to your additions, imo. But If you'd like you could take a look at them. I'll merge `staging` in `master` and publish it to Chrome now.

**Comment by vunderkind** [comment]
Ah, I didn't notice those. 

Yeah, sure — I'll work on these as well. I need the extension to perform to the same level of quality as it always did. I'll send you a new PR when I have it ready.

**Comment by Naramsim** [comment]
Hi @vunderkind , thanks so much for the support but please take it easy :)

**Comment by vunderkind** [comment]
Thank you @Naramsim! — I've actually detected a bug in my implementation so I'm gonna have to send in another PR soon. I'll roll it together with your other notes.

**Review by HOLYGHOST1111 — COMMENTED** [review]
#107

**Review by HOLYGHOST1111 — COMMENTED** [review]
<details>
<summary>Details</summary>



</details>

**Pull request merged**
