### PR TITLE
refactor(date-calculation): using moment.js for date calculation

### PR DESCRIPTION
**Pull request by sarbbottam**
using moment.js for date calculation.

### CODE REVIEW

**Comment by sarbbottam** [comment]
Could you do me a favor, while merging? Could you squash and merge instead of merge?

**Comment by Naramsim** [comment]
Squashed, anyhow why would you squash and merge?

**Comment by sarbbottam** [comment]
> anyhow why would you squash and merge?

To keep the commit history clean, avoiding the merge commit. See the last two merge.

screen_shot_2016-06-16_at_8_10_01_am

**Comment by Naramsim** [comment]
All clear, great point

**Pull request merged**
